### ISSUE TITLE
empty menu in blender 4.1

### ISSUE THREAD

**Issue by clicktodev** [markelekdotcom/color-ramp-converter#3] opened 2024-09-26 17:52 UTC
the color ramp converter menu is empty

![image](https://github.com/user-attachments/assets/4f5749e5-b3b8-4443-861b-eb8cd998a4f8)

**Comment by markelekdotcom** [comment] 2024-10-01 21:37
Hi there, 

It looks like this is a duplicate of issue #2 📝.

Please take a look at this issue comment: 
https://github.com/markelekdotcom/color-ramp-converter/issues/2#issuecomment-1906058607 
or the documentation:
https://colorrampconverter.readthedocs.io/en/latest/installation.html#installation-issues 
for a potential solution.

Hope this helps!

If you believe this is a diferent issue, feel free to open a new issue and provide more details.

All the best,
Mark

**Closed as completed by markelekdotcom** 2024-10-01 21:37 UTC

**Comment by clicktodev** [comment] 2024-10-02 00:30
thanks it worked! the problem was with the folder name indeed
